### ISSUE TITLE
Incorrect error messages on old binaris.yml

### ISSUE THREAD

**Issue by arielshaqed** [binaris/binaris#268]
```
flutterby:my-function ariels$ cat binaris.yml
functions:
  waste:
    file: waste.js
    entrypoint: busy

flutterby:my-function ariels$ bn deploy waste
binaris.yml: field: <file> should be a string
```
