### ISSUE TITLE
"Could not connect to Binaris backend" caused by YAML format errors

### ISSUE THREAD

**Issue by adamatan** [binaris/binaris#367]
# The Problem
`binaris.yml` validation/format errors produce a generic `Could not connect to Binaris backend` message which is useless for debugging.

## Steps To Reproduce
I have deployed a function with a malformed `binaris.yml` `env` section, without a `:` suffix on the entries.

```
functions:
  handleTrelloEvent:
    file: handleTrelloEvent.js
    entrypoint: handler
    runtime: node8
  listWebhooks:
    file: listWebhooks.js
    entrypoint: handler
    runtime: node8
    env:
      TRELLO_API_KEY   <-----
      TRELLO_TOKEN     <-----
```

Upon deployment of the second function, the following error appeared:
```
Could not connect to Binaris backend
```

The first function, `handleTrelloEvent`, was deployed without any problems.

## Debug output
`BINARIS_LOG_LEVEL=debug` gives:

        ...
        toJSON: [Function: responseToJSON],
        caseless:
         Caseless {
           dict:
            { date: 'Sun, 04 Nov 2018 11:49:46 GMT',
              'content-type': 'application/json; charset=utf-8',
              'content-length': '279',
              connection: 'keep-alive',
              'x-powered-by': 'Express',
              etag: 'W/"117-t0rgb2tsf1KQoQsVnqAlEd1PD8E"' } },
        read: [Function],
        body:
         { errorCode: 'ERR_BAD_REQUEST',
           message: 'Invalid request parameters (see errors field)',
           errors:
            [ { keyword: 'type',
                dataPath: '.env',
                schemaPath: '#/properties/env/type',
                params: { type: 'object' },
                message: 'should be object' } ],
           debugId: 'be7df41c-7bba-4713-848b-9db852c52601' } } } }

# Expected Behaviour
Validation errors in `binaris.yml` should give explicit error messages with a clear indication to the location of the problem. If possible, these validations should be performed locally to reduce the duration of the debugging cycles.
